sudo: required # for Trusty
dist: trusty

language: cpp

compiler:
        - gcc
        - clang

before_install:
        - sudo add-apt-repository --yes ppa:gnome3-team/gnome3-staging # for recent HarfBuzz
        - sudo apt-get update -qq
        - sudo apt-get install -qq libxml2-dev libharfbuzz-dev
                                   libcairo2-dev libgtk-3-dev
                                   qtbase5-dev qt5-default

script:
        - ./autogen.sh
        - ./configure
        - make

